require:
  - rubocop-rails
AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/**/*'
    - 'vendor/**/*'

Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
